index:
    path: /
    controller: App\Controller\DefaultController::index

about:
    path: /about
    controller: App\Controller\DefaultController::about

accounts:
    path: /accounts
    controller: App\Controller\AccountController::index

account_new:
    path: /account/new
    controller: App\Controller\AccountController::new

account_create:
    path: /account/create
    controller: App\Controller\AccountController::create

account_edit:
    path: /account/edit/{id}
    controller: App\Controller\AccountController::edit

account_update:
    path: /account/update/{id}
    controller: App\Controller\AccountController::update

account_show:
    path: /account/show/{id}
    controller: App\Controller\AccountController::show

account_delete:
    path: /acount/delete/{id}
    controller: App\Controller\AccountController::delete

